### ISSUE TITLE
How to use Paper or other jars

### ISSUE THREAD

**Issue by SalmanYamin199** [lordofwizard/minecraft_server#1]
Hey man how to use the paper or spigot or any other jar files ? Can I use it just by downloading a paper mc jar and rename it to server.jar?
I am a Noob so any help is much appreciated.

**Comment by lordofwizard** [comment]
Well you can paste the url when you download the server. I wont' recommend doing that until the next week cause i have made some improvements on the livestreams. That feature is now completely working and perfect.. Wait 2 days and you will get your hands on it : ) Thanks
